- name: Installer la stack de monitoring (Prometheus, Grafana, Loki)
  hosts: api
  become: yes
  collections:
    - community.docker

  vars:
    monitoring_dir: "/opt/monitoring"

  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - python3-pip
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Python SDK
      pip:
        name: docker
        state: present

    - name: Check if Docker Compose v2 is available
      shell: docker compose version
      register: docker_compose_check
      changed_when: false
      failed_when: false

    - name: Create docker CLI plugins directory
      file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
        mode: '0755'

    - name: Install Docker Compose v2 binary if not present
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.24.2/docker-compose-linux-x86_64"
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: '0755'
      when: docker_compose_check.rc != 0

    - name: Create monitoring directory
      file:
        path: "{{ monitoring_dir }}"
        state: directory
        owner: "debian"
        mode: "0755"

    - name: Copy monitoring configuration files (Prometheus, Grafana, Loki)
      copy:
        src: "../monitoring/{{ item }}"
        dest: "{{ monitoring_dir }}/"
        owner: "debian"
      loop:
        - prometheus
        - grafana
        - loki

    - name: Generate Docker Compose file for monitoring stack
      template:
        src: ./monitoring/docker-compose.yml.j2
        dest: "{{ monitoring_dir }}/docker-compose.yml"
        owner: "debian"
        mode: "0644"

    - name: Deploy Docker Compose stack for monitoring
      community.docker.docker_compose_v2:
        project_src: "{{ monitoring_dir }}"
        state: present
        recreate: always
      register: output

    - name: Display Docker Compose output
      debug:
        var: output